-- Creating 5 new tables for new db design
CREATE TABLE Suppliers (
		SUPPLIER_ID int NOT NULL AUTO_INCREMENT,
		SUPPLIER_NAME varchar(50) NOT NULL,
		SUPP_CONTACT_NAME varchar(50) NOT NULL,
		SUPP_ADDRESS varchar(200) NOT NULL,
		SUPP_NUMBER1 varchar(200) NOT NULL,
		SUPP_NUMBER2 varchar(200),
		SUPP_EMAIL varchar(200) NOT NULL,
		primary key (SUPPLIER_ID)
);

CREATE TABLE Invoices ( 
		INVOICE_ID int NOT NULL AUTO_INCREMENT,
		INVOICE_REF varchar(200) NOT NULL,
		PRIMARY KEY (INVOICE_ID)
);

CREATE TABLE Orders ( 
        ORDER_ID int NOT NULL AUTO_INCREMENT,
        ORDER_REF varchar(10) NOT NULL, 
        ORDER_DATE date NOT NULL, 
        SUPPLIER_ID int NOT NULL,
        PRIMARY KEY (ORDER_ID),
        FOREIGN KEY (SUPPLIER_ID) REFERENCES suppliers(SUPPLIER_ID)
);

CREATE TABLE Order_Items(
		ORDER_ITEM_ID int NOT NULL AUTO_INCREMENT,
		ORDER_ITEM_DESCRIPTION varchar(200),
		ORDER_ITEM_STATUS varchar(200),
		ORDER_ITEM_LINE_AMOUNT int,
		ORDER_ITEM_TOTAL_AMOUNT int,
		INVOICE_ID int,
		ORDER_ID int,
		PRIMARY KEY (ORDER_ITEM_ID),
		FOREIGN KEY (ORDER_ID) REFERENCES Orders(ORDER_ID),
		FOREIGN KEY (INVOICE_ID) REFERENCES invoices(INVOICE_ID)
);

CREATE TABLE Invoice_details ( 
		INVOICE_DETAILS_ID int NOT NULL AUTO_INCREMENT,
		INVOICE_DETAILS_AMOUNT int,
		INVOICE_DETAILS_DATE date NOT NULL,
		INVOICE_DETAILS_STATUS varchar(200),
		INVOICE_DETAILS_HOLD_REASON varchar(200),
		INVOICE_ID int NOT NULL,
		PRIMARY KEY (INVOICE_DETAILS_ID),
		FOREIGN KEY (INVOICE_ID) REFERENCES Invoices(INVOICE_ID)
);